// YarKeshavarz Offline Global Brain V1 - entity and intent engine
import brain from "./global-agriculture-brain.js";
function normalize(t=""){return String(t).toLowerCase().replace(/[يى]/g,"ی").replace(/ك/g,"ک").replace(/\u200c/g," ").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/[^\p{L}\p{N}\s]/gu," ").replace(/\s+/g," ").trim();}
function exact(text,term){const a=normalize(text).split(" ").filter(Boolean),b=normalize(term).split(" ").filter(Boolean);if(!b.length)return false;if(b.length===1)return a.includes(b[0]);for(let i=0;i<=a.length-b.length;i++){let ok=true;for(let j=0;j<b.length;j++)if(a[i+j]!==b[j]){ok=false;break;}if(ok)return true;}return false;}
const intentMap={definition:["چیست","چیه","تعریف","معنی","یعنی"],irrigation:["آبیاری","آبدهی","کم آبی","تنش خشکی"],fertilizer:["کود","کوددهی","تغذیه","اوره","ازت","نیتروژن","فسفر","پتاس"],soil:["خاک","پی اچ","ph","ec خاک","شوری خاک","زهکشی","ماده آلی","بافت خاک"],pest:["آفت","شته","کنه","سفیدبالک","تریپس","کرم"],disease:["بیماری","قارچ","باکتری","ویروس","پوسیدگی","لکه","سفیدک","زنگ"],weed:["علف هرز","علفکش","هرز"],planting:["کاشت","بذر","نشا","تراکم","فاصله کاشت","تاریخ کاشت"],harvest:["برداشت","رسیدگی","بلوغ","خشک کردن","انبار","سردخانه"],greenhouse:["گلخانه","هیدروپونیک","کوکوپیت","پرلیت","تهویه"],economics:["هزینه","درآمد","سود","قیمت","اقتصاد","سرمایه","نقطه سربه سر"],machinery:["تراکتور","سمپاش","کمباین","دروگر","نازل"],livestock:["دام","گاو","گوسفند","بز","مرغ","طیور","جیره"],beekeeping:["زنبور","کندو","ملکه","عسل"],climate:["هوا","دما","یخبندان","گرما","سرما","بارندگی","رطوبت","خشکسالی"],precision:["کشاورزی دقیق","gps","پهپاد","ماهواره","نقشه","سنجش از دور"],management:["مزرعه","زمین","قطعه","برنامه کشت","ثبت عملیات","موجودی"]};
export function detectIntent(text=""){const q=normalize(text);let best={id:"general",score:0};for(const [id,words] of Object.entries(intentMap)){const s=words.reduce((n,w)=>n+(exact(q,w)?2:0),0);if(s>best.score)best={id,score:s};}return best;}
export function detectCrop(text=""){const q=normalize(text);let best=null;for(const c of brain.crops?Object.values(brain.crops).flat():[]){if(exact(q,c))best={crop:c,matched:c,score:12};}for(const [alias,crop] of Object.entries(brain.aliases||{})){if(exact(q,alias)&&(!best||best.score<12))best={crop,matched:alias,score:10};}return best;}
export function hasExplicitCropLikeText(text=""){const q=normalize(text);return /(کاشت|کشت|پرورش|آبیاری|کوددهی|بیماری|آفت|قیمت|هزینه|برای)\s+\S+/.test(q) || !!detectCrop(q);}
export function extractEntities(text=""){return {crop:detectCrop(text),intent:detectIntent(text),explicitCropLike:hasExplicitCropLikeText(text)};}
export default {detectIntent,detectCrop,extractEntities};
