import baseDB from "./agriculture-db-extended.js";
import brain from "./global-agriculture-brain.js";
import {extractEntities} from "./intent-engine.js";
import {remember,contextHint} from "./context-engine.js";
const KNOWLEDGE_KEY="yk-admin-knowledge-v1";
function normalize(t=""){return String(t).toLowerCase().replace(/[يى]/g,"ی").replace(/ك/g,"ک").replace(/\u200c/g," ").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/[^\p{L}\p{N}\s]/gu," ").replace(/\s+/g," ").trim();}
const STOP=new Set(["چیست","چیه","چه","چگونه","چطور","چرا","کی","زمان","زمانی","است","هست","هستند","دارد","دارند","شود","باید","برای","در","از","به","با","را","که","این","آن","یک","و","یا","من","می","کنم","کنیم","کنید","مناسب","لازم","نیاز","پیشنهاد"]);
function toks(t){return normalize(t).split(" ").filter(x=>x.length>1&&!STOP.has(x));}
function contains(text,term){const a=normalize(text).split(" ").filter(Boolean),b=normalize(term).split(" ").filter(Boolean);if(!b.length)return false;if(b.length===1)return a.includes(b[0]);for(let i=0;i<=a.length-b.length;i++){let ok=true;for(let j=0;j<b.length;j++)if(a[i+j]!==b[j]){ok=false;break;}if(ok)return true;}return false;}
function managerDB(){try{const d=JSON.parse(localStorage.getItem(KNOWLEDGE_KEY)||"[]");return Array.isArray(d)?d.map(x=>({category:"مدیریت",topic:x.title||x.topic||"دانش مدیریت",keywords:x.keywords||[],general:x.answer||x.general||"",solution:x.solution||""})):[]}catch{return[]}}
function score(q,qt,item,e){let s=0;const topic=normalize(item.topic||"");if(topic&&q===topic)s+=45;if(topic&&contains(q,topic))s+=20;for(const t of toks(topic))if(qt.includes(t))s+=5;for(const raw of item.keywords||[]){const k=normalize(raw);if(contains(q,k))s+=k.includes(" ")?11:7;}
if(e.crop?.crop&&contains(topic,e.crop.crop))s+=16;if(e.intent?.id&&normalize(item.category||"").includes(e.intent.id))s+=3;return s;}
export function searchKnowledge(question){const q=normalize(question),entities=extractEntities(q),e=contextHint(entities,q),db=[...(Array.isArray(baseDB)?baseDB:[]),...(brain.records||[]),...managerDB()];const ranked=db.map(item=>({item,score:score(q,toks(q),item,e)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);return {item:ranked[0]?.item||null,score:ranked[0]?.score||0,ranked:ranked.slice(0,3),entities:e};}
function clarification(q,r){if(r.entities?.explicitCropLike&&!r.entities?.crop?.crop)return "🌱 محصول جدیدت را دیدم، اما هنوز آن محصول در دانش آفلاین من با اطمینان شناسایی نشده است. نام محصول را دقیق بنویس یا همراهش منطقه و مرحله رشد را بگو تا پاسخ عمومیِ امن بدهم؛ من محصول قبلی گفتگو را جایگزینش نمی‌کنم.";return "🌱 برای این سؤال تطبیق مطمئن کافی پیدا نکردم. نام محصول، مشکل، مرحله رشد یا شرایط زمین را دقیق‌تر بنویس؛ مثلاً «گل محمدی، آبیاری تابستان» یا «گندم، برگ زرد».";}
function buildAnswer(item,e){let a=`🌱 ${item.topic||"موضوع کشاورزی"}\n\n`;if(item.symptoms)a+=`🔎 نشانه‌ها:\n${item.symptoms}\n\n`;if(item.cause)a+=`⚠️ علت یا توضیح:\n${item.cause}\n\n`;if(item.general)a+=item.general+"\n\n";if(item.solution)a+=`✅ راهکار کلی:\n${item.solution}\n\n`;if(e.intent?.id==="irrigation")a+="💧 مقدار و زمان آبیاری به مرحله رشد، بافت خاک، رطوبت و کیفیت آب وابسته است.\n\n";if(e.intent?.id==="fertilizer")a+="🧪 نسخه دقیق کود بهتر است بر پایه آزمون خاک/برگ، کیفیت آب و نیاز مرحله رشد تنظیم شود.\n\n";return (a+"ℹ️ برای سموم و درمان‌های حساس، برچسب رسمی، قوانین محلی و نظر کارشناس را هم در نظر بگیر.").trim();}
export function findOfflineAnswer(question=""){const q=normalize(question);if(!q)return "🌱 سؤال کشاورزی‌ات را بنویس.";const r=searchKnowledge(q);remember("user",question,r.entities);if(!r.item||r.score<7)return clarification(q,r);const a=buildAnswer(r.item,r.entities);remember("bot",a,r.entities);return a;}
export default findOfflineAnswer;
if(typeof window!=="undefined")window.YarKeshavarzOffline={findOfflineAnswer,searchKnowledge};
